apiVersion: v1
kind: ServiceAccount
metadata:
  name: jmeter-master
  namespace: jmeter
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jmeter-master-discovery
  namespace: jmeter
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jmeter-master-discovery
  namespace: jmeter
subjects:
  - kind: ServiceAccount
    name: jmeter-master
    namespace: jmeter
roleRef:
  kind: Role
  name: jmeter-master-discovery
  apiGroup: rbac.authorization.k8s.io
